In [1]:
import pandas as pd

df = pd.read_csv("Bengaluru_House_Data.csv")
df.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [2]:
df.shape
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [3]:
df = df.drop(['area_type','availability','society','balcony'], axis=1)
df = df.dropna()
df.isnull().sum()

location      0
size          0
total_sqft    0
bath          0
price         0
dtype: int64

In [4]:
df['size'] = df['size'].apply(lambda x: int(x.split(' ')[0]))
df.rename(columns={'size':'bhk'}, inplace=True)
df.head()

                   location  bhk total_sqft  bath   price
0  Electronic City Phase II    2       1056   2.0   39.07
1          Chikka Tirupathi    4       2600   5.0  120.00
2               Uttarahalli    3       1440   2.0   62.00
3        Lingadheeranahalli    3       1521   3.0   95.00
4                  Kothanur    2       1200   2.0   51.00

In [5]:
def convert_sqft(x):
    if '-' in x:
        a = x.split('-')
        return (float(a[0]) + float(a[1])) / 2
    try:
        return float(x)
    except:
        return None

df['total_sqft'] = df['total_sqft'].apply(convert_sqft)
df = df.dropna()
df.head()

                   location  bhk  total_sqft  bath   price
0  Electronic City Phase II    2      1056.0   2.0   39.07
1          Chikka Tirupathi    4      2600.0   5.0  120.00
2               Uttarahalli    3      1440.0   2.0   62.00
3        Lingadheeranahalli    3      1521.0   3.0   95.00
4                  Kothanur    2      1200.0   2.0   51.00

In [6]:
df['price_per_sqft'] = df['price'] * 100000 / df['total_sqft']
df.head()

                   location  bhk  total_sqft  bath   price  price_per_sqft
0  Electronic City Phase II    2      1056.0   2.0   39.07     3699.810606
1          Chikka Tirupathi    4      2600.0   5.0  120.00     4615.384615
2               Uttarahalli    3      1440.0   2.0   62.00     4305.555556
3        Lingadheeranahalli    3      1521.0   3.0   95.00     6245.890861
4                  Kothanur    2      1200.0   2.0   51.00     4250.000000

In [7]:
df['location'] = df['location'].apply(lambda x: x.strip())
location_stats = df['location'].value_counts()
location_stats_less_than_10 = location_stats[location_stats <= 10]

df['location'] = df['location'].apply(lambda x: 'other' if x in location_stats_less_than_10 else x)
df.head()

                   location  bhk  total_sqft  bath   price  price_per_sqft
0  Electronic City Phase II    2      1056.0   2.0   39.07     3699.810606
1          Chikka Tirupathi    4      2600.0   5.0  120.00     4615.384615
2               Uttarahalli    3      1440.0   2.0   62.00     4305.555556
3        Lingadheeranahalli    3      1521.0   3.0   95.00     6245.890861
4                  Kothanur    2      1200.0   2.0   51.00     4250.000000

In [8]:
df = df[~(df['total_sqft']/df['bhk'] < 300)]
df.shape

(12456, 6)

In [9]:
import numpy as np

def remove_pps_outliers(df):
    df_out = pd.DataFrame()
    for key, subdf in df.groupby('location'):
        m = np.mean(subdf.price_per_sqft)
        st = np.std(subdf.price_per_sqft)
        reduced_df = subdf[(subdf.price_per_sqft > (m - st)) & (subdf.price_per_sqft <= (m + st))]
        df_out = pd.concat([df_out, reduced_df], ignore_index=True)
    return df_out

df = remove_pps_outliers(df)
df.shape

(10242, 6)

In [10]:
def remove_bhk_outliers(df):
    exclude_indices = np.array([])
    for location, location_df in df.groupby('location'):
        bhk_stats = {}
        for bhk, bhk_df in location_df.groupby('bhk'):
            bhk_stats[bhk] = {
                'mean': np.mean(bhk_df.price_per_sqft),
                'std': np.std(bhk_df.price_per_sqft),
                'count': bhk_df.shape[0]
            }
        for bhk, bhk_df in location_df.groupby('bhk'):
            stats = bhk_stats.get(bhk-1)
            if stats and stats['count'] > 5:
                exclude_indices = np.append(
                    exclude_indices,
                    bhk_df[bhk_df.price_per_sqft < stats['mean']].index.values
                )
    return df.drop(exclude_indices, axis='index')

df = remove_bhk_outliers(df)
df.shape

(7317, 6)

In [11]:
df = df.drop(['price_per_sqft'], axis=1)
df.head()

              location  bhk  total_sqft  bath  price
0  1st Block Jayanagar    4      2850.0   4.0  428.0
1  1st Block Jayanagar    3      1630.0   3.0  194.0
2  1st Block Jayanagar    3      1875.0   2.0  235.0
3  1st Block Jayanagar    3      1200.0   2.0  130.0
4  1st Block Jayanagar    2      1235.0   2.0  148.0

In [12]:
dummies = pd.get_dummies(df['location'])
df = pd.concat([df, dummies.drop('other', axis=1)], axis=1)
df = df.drop('location', axis=1)
df.head()

,bhk,total_sqft,bath,price,1st Block Jayanagar,1st Phase JP Nagar,2nd Phase Judicial Layout,2nd Stage Nagarbhavi,5th Block Hbr Layout,5th Phase JP Nagar,...,Vijayanagar,Vishveshwarya Layout,Vishwapriya Layout,Vittasandra,Whitefield,Yelachenahalli,Yelahanka,Yelahanka New Town,Yelenahalli,Yeshwanthpur
0,4,2850.0,4.0,428.0,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,3,1630.0,3.0,194.0,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,3,1875.0,2.0,235.0,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,3,1200.0,2.0,130.0,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,2,1235.0,2.0,148.0,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [13]:
X = df.drop('price', axis=1)
y = df['price']

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=10)

In [15]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)
model.score(X_test, y_test)

0.817588996546711

In [16]:
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_val_score

cv = ShuffleSplit(n_splits=5, test_size=0.2, random_state=0)

scores = cross_val_score(LinearRegression(), X, y, cv=cv)
scores

array([0.83458131, 0.8720703 , 0.77477801, 0.86043362, 0.87857309])

In [18]:
import pickle

with open('bangalore_home_prices_model.pickle', 'wb') as f:
    pickle.dump(model, f)

In [19]:
import os
os.getcwd()

'C:\\Users\\MUHAMMAD AZHAAN\\Downloads\\bengaluru-house-price-data'

In [20]:
X.columns

Index(['bhk', 'total_sqft', 'bath', '1st Block Jayanagar',
       '1st Phase JP Nagar', '2nd Phase Judicial Layout',
       '2nd Stage Nagarbhavi', '5th Block Hbr Layout', '5th Phase JP Nagar',
       '6th Phase JP Nagar',
       ...
       'Vijayanagar', 'Vishveshwarya Layout', 'Vishwapriya Layout',
       'Vittasandra', 'Whitefield', 'Yelachenahalli', 'Yelahanka',
       'Yelahanka New Town', 'Yelenahalli', 'Yeshwanthpur'],
      dtype='object', length=243)

In [21]:
list(X.columns)

['bhk',
 'total_sqft',
 'bath',
 '1st Block Jayanagar',
 '1st Phase JP Nagar',
 '2nd Phase Judicial Layout',
 '2nd Stage Nagarbhavi',
 '5th Block Hbr Layout',
 '5th Phase JP Nagar',
 '6th Phase JP Nagar',
 '7th Phase JP Nagar',
 '8th Phase JP Nagar',
 '9th Phase JP Nagar',
 'AECS Layout',
 'Abbigere',
 'Akshaya Nagar',
 'Ambalipura',
 'Ambedkar Nagar',
 'Amruthahalli',
 'Anandapura',
 'Ananth Nagar',
 'Anekal',
 'Anjanapura',
 'Ardendale',
 'Arekere',
 'Attibele',
 'BEML Layout',
 'BTM 2nd Stage',
 'BTM Layout',
 'Babusapalaya',
 'Badavala Nagar',
 'Balagere',
 'Banashankari',
 'Banashankari Stage II',
 'Banashankari Stage III',
 'Banashankari Stage V',
 'Banashankari Stage VI',
 'Banaswadi',
 'Banjara Layout',
 'Bannerghatta',
 'Bannerghatta Road',
 'Basavangudi',
 'Basaveshwara Nagar',
 'Battarahalli',
 'Begur',
 'Begur Road',
 'Bellandur',
 'Benson Town',
 'Bharathi Nagar',
 'Bhoganhalli',
 'Billekahalli',
 'Binny Pete',
 'Bisuvanahalli',
 'Bommanahalli',
 'Bommasandra',
 'Bommasandra Industrial Area',
 'Bommenahalli',
 'Brookefield',
 'Budigere',
 'CV Raman Nagar',
 'Chamrajpet',
 'Chandapura',
 'Channasandra',
 'Chikka Tirupathi',
 'Chikkabanavar',
 'Chikkalasandra',
 'Choodasandra',
 'Cooke Town',
 'Cox Town',
 'Cunningham Road',
 'Dasanapura',
 'Dasarahalli',
 'Devanahalli',
 'Devarachikkanahalli',
 'Dodda Nekkundi',
 'Doddaballapur',
 'Doddakallasandra',
 'Doddathoguru',
 'Domlur',
 'Dommasandra',
 'EPIP Zone',
 'Electronic City',
 'Electronic City Phase II',
 'Electronics City Phase 1',
 'Frazer Town',
 'GM Palaya',
 'Garudachar Palya',
 'Giri Nagar',
 'Gollarapalya Hosahalli',
 'Gottigere',
 'Green Glen Layout',
 'Gubbalala',
 'Gunjur',
 'HAL 2nd Stage',
 'HBR Layout',
 'HRBR Layout',
 'HSR Layout',
 'Haralur Road',
 'Harlur',
 'Hebbal',
 'Hebbal Kempapura',
 'Hegde Nagar',
 'Hennur',
 'Hennur Road',
 'Hoodi',
 'Horamavu Agara',
 'Horamavu Banaswadi',
 'Hormavu',
 'Hosa Road',
 'Hosakerehalli',
 'Hoskote',
 'Hosur Road',
 'Hulimavu',
 'ISRO Layout',
 'ITPL',
 'Iblur Village',
 'Indira Nagar',
 'JP Nagar',
 'Jakkur',
 'Jalahalli',
 'Jalahalli East',
 'Jigani',
 'Judicial Layout',
 'KR Puram',
 'Kadubeesanahalli',
 'Kadugodi',
 'Kaggadasapura',
 'Kaggalipura',
 'Kaikondrahalli',
 'Kalena Agrahara',
 'Kalyan nagar',
 'Kambipura',
 'Kammanahalli',
 'Kammasandra',
 'Kanakapura',
 'Kanakpura Road',
 'Kannamangala',
 'Karuna Nagar',
 'Kasavanhalli',
 'Kasturi Nagar',
 'Kathriguppe',
 'Kaval Byrasandra',
 'Kenchenahalli',
 'Kengeri',
 'Kengeri Satellite Town',
 'Kereguddadahalli',
 'Kodichikkanahalli',
 'Kodigehaali',
 'Kodigehalli',
 'Kodihalli',
 'Kogilu',
 'Konanakunte',
 'Koramangala',
 'Kothannur',
 'Kothanur',
 'Kudlu',
 'Kudlu Gate',
 'Kumaraswami Layout',
 'Kundalahalli',
 'LB Shastri Nagar',
 'Laggere',
 'Lakshminarayana Pura',
 'Lingadheeranahalli',
 'Magadi Road',
 'Mahadevpura',
 'Mahalakshmi Layout',
 'Mallasandra',
 'Malleshpalya',
 'Malleshwaram',
 'Marathahalli',
 'Margondanahalli',
 'Marsur',
 'Mico Layout',
 'Munnekollal',
 'Murugeshpalya',
 'Mysore Road',
 'NGR Layout',
 'NRI Layout',
 'Nagarbhavi',
 'Nagasandra',
 'Nagavara',
 'Nagavarapalya',
 'Narayanapura',
 'Neeladri Nagar',
 'Nehru Nagar',
 'OMBR Layout',
 'Old Airport Road',
 'Old Madras Road',
 'Padmanabhanagar',
 'Pai Layout',
 'Panathur',
 'Parappana Agrahara',
 'Pattandur Agrahara',
 'Poorna Pragna Layout',
 'Prithvi Layout',
 'R.T. Nagar',
 'Rachenahalli',
 'Raja Rajeshwari Nagar',
 'Rajaji Nagar',
 'Rajiv Nagar',
 'Ramagondanahalli',
 'Ramamurthy Nagar',
 'Rayasandra',
 'Sahakara Nagar',
 'Sanjay nagar',
 'Sarakki Nagar',
 'Sarjapur',
 'Sarjapur  Road',
 'Sarjapura - Attibele Road',
 'Sector 2 HSR Layout',
 'Sector 7 HSR Layout',
 'Seegehalli',
 'Shampura',
 'Shivaji Nagar',
 'Singasandra',
 'Somasundara Palya',
 'Sompura',
 'Sonnenahalli',
 'Subramanyapura',
 'Sultan Palaya',
 'TC Palaya',
 'Talaghattapura',
 'Thanisandra',
 'Thigalarapalya',
 'Thubarahalli',
 'Tindlu',
 'Tumkur Road',
 'Ulsoor',
 'Uttarahalli',
 'Varthur',
 'Varthur Road',
 'Vasanthapura',
 'Vidyaranyapura',
 'Vijayanagar',
 'Vishveshwarya Layout',
 'Vishwapriya Layout',
 'Vittasandra',
 'Whitefield',
 'Yelachenahalli',
 'Yelahanka',
 'Yelahanka New Town',
 'Yelenahalli',
 'Yeshwanthpur']

In [6]:
import pandas as pd

df = pd.read_csv("Bengaluru_House_Data.csv")

In [7]:
df = df.drop(['area_type','availability','society','balcony'], axis=1)
df = df.dropna()

df['size'] = df['size'].apply(lambda x: int(x.split(' ')[0]))
df.rename(columns={'size':'bhk'}, inplace=True)

def convert_sqft(x):
    if '-' in x:
        a = x.split('-')
        return (float(a[0]) + float(a[1])) / 2
    try:
        return float(x)
    except:
        return None

df['total_sqft'] = df['total_sqft'].apply(convert_sqft)
df = df.dropna()

df['price_per_sqft'] = df['price'] * 100000 / df['total_sqft']

In [ ]:
dummies = pd.get_dummies(df['location'])
df = pd.concat([df, dummies.drop('other', axis=1)], axis=1)
df = df.drop('location', axis=1)